### PR TITLE
Add tests for cache types

### PR DESCRIPTION
**Pull request by northernSage**
- [x] add tests.yaml workflow
- [x] redis 
- [x] memcached
- [x] simple cache
- [x] file system
- [x] uwsgi
- [x] update coverage and testing sections in `CONTRIBUTING.rst`

### CODE REVIEW

**Comment by davidism** [comment]
Just a heads up, make sure these tests are rock solid, we had to remove the cache tests when they were still in Werkzeug because they randomly failed constantly in unrelated PRs and caused confusion.

**Comment by northernSage** [comment]
Hey, thanks for the heads up. I remember seeing something about how the previous test suite was flaky on Werkzeug history when writing #13 so I have been doing some tests on my side and taking my time with this PR (this is why I haven't merged it along with #24). That being said, the current test suite will fail when testing [entry expiration time](https://github.com/pallets/cachelib/pull/25/files#diff-e52e4ddd58b7ef887ab03c04116e676f6280b824ab7469d5d3080e5cba4f2128R118) without #26 since non-expired entries that fit `idx % 3 == 0 `will be removed. So we can either hold this PR until I'm done with #26 or remove the expiration time test, merge this now and submit a third PR later after merging #26 with the missing expiration tests. What do you think @davidism ?

**Comment by davidism** [comment]
Let's see what happens with #26

**Comment by northernSage** [comment]
I have just finished testing with #26 and #31 changes applied and all tests are passing consistently on my env with tox for py36, py37 and py38. #31 was also necessary since memcached was not initializing entries to -delta/delta (as described in the PR) so [increment/decrement tests](https://github.com/pallets/cachelib/pull/25/files#diff-e52e4ddd58b7ef887ab03c04116e676f6280b824ab7469d5d3080e5cba4f2128R111) were failing.

**Comment by northernSage** [comment]
Uwsgi tests were throwing a `SystemError: <class 'DeprecationWarning'> returned a result with an error set` on execution of any `uwsgi` command using their python-plugin. The deprecation warning is question was `DeprecationWarning: PY_SSIZE_T_CLEAN will be required for '#' formats.` That seemed like a Python/C-layer problem in `uwsgi`, so I found that [issue36381](https://bugs.python.org/issue36381) introduced a deprecation warning about an upcoming Python C API change. The meaning of `PY_SSIZE_T_CLEAN` can be found in [Python/C strings-and-buffers docs](https://python.readthedocs.io/en/stable/c-api/arg.html#strings-and-buffers), but to sum up:       
                                                                                                   
All buffers "#" variants of formats s#, y#, etc. can have either `int` or `Py_ssize_t` as type for their length argument. Which one is used is decided by defining the said `PY_SSIZE_T_CLEAN` macro. **This behaviour will change in a future Python version to only support `Py_ssize_t` and drop `int` support so the python docs advise to always define `PY_SSIZE_T_CLEAN`.**                                       
                                                                                                   
The `DeprecationWarning` was introduced in py3.8 and it should work fine for lower releases but this might get troublesome in the future. Here is the respective [CPython PR that introduced the changes](https://github.com/python/cpython/commit/0895793194cd5f1153d2a286ed3a4fc876149b16) in case anyone is interested.

We can use [pytest warning capture ](https://docs.pytest.org/en/6.2.x/warnings.html#warnings-capture) to get around this for now by passing `-W default::DeprecationWarning` so the warning still shows but will not be converted to an error. Something will need to be done in the future to avoid a possible break with py38 and higher (assuming the issue isn't handled at the C layer by Uwsgi) so i'm not sure what our next step should be here, WDYT @davidism ?

**Comment by davidism** [comment]
Add it to the `filterwarnings` pytest option in `setup.cfg`.

**Comment by northernSage** [comment]
uwsgi cleans expired entries on a separate [sweeper thread](https://uwsgi-docs.readthedocs.io/en/latest/Caching.html#the-cache-sweeper-thread) and so far I have found no documented way of triggering the cleaning. This might make [expiration related](https://github.com/pallets/cachelib/pull/25/files#diff-e52e4ddd58b7ef887ab03c04116e676f6280b824ab7469d5d3080e5cba4f2128R164) tests specially tricky.

**Pull request merged**
